apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.20.8
    anywhere.eks.amazonaws.com/skip-ip-check: "true"
  name: eksa-dell-mgmt
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.69.201.188
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: eksa-dell-mgmt-cp
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: eksa-dell-mgmt
  eksaVersion: v0.20.8
  gitOpsRef:
    kind: FluxConfig
    name: eksa-dell-mgmt
  kubernetesVersion: "1.29"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 20m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: eksa-dell-mgmt

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: eksa-dell-mgmt
  namespace: default
spec:
  hookImagesURLPath: http://10.69.201.5:8000/hookos
  osImageURL: http://10.69.201.5:8000/v1_29/ubuntu-2204-kube-1-29.gz
  tinkerbellIP: 10.69.201.189

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-dell-mgmt-cp
  namespace: default
spec:
  hardwareSelector:
    type: cp
  osFamily: ubuntu
  osImageURL: ""
  templateRef: {}
  users:
  - name: dell-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfepmsOV+kKh92d0k+d5yZc+mQdXoNhTESqIjt4IOuYgsFrNsuAfepq/KgwPCmuaLR3xBRvQAPYOCTBKBnMD5gm9UmigUefq1B8RFVDsf9AM5KH6QJ5uvYbNPZYlSX16XGEGipj0lyzr3JvOd6aGzu2aN5NIpd1O6RWYMP8CNaGJk0uHL3F/U+cRAzALTVHsio5htuUHjAZPzhs8eNGvaA7l5k+uIXtHrkYmwRoqRNu5VZkP0PdSq4dT9e+xe0/HF0A6H1zeYshd7fQ8Irm8AyKmCRRnm4TlcBc6mGn4GJfBOu7LlL3MLHkU2wMObPsBYPgIa74XqomPvBfJibmu/Jr9WlStmx79SH5MEQAitbbZMk1PGTz1Hm8/4839T6AffH+tKXE9nKgEB0jfAwzfxFVFQGvlwgfm7IuDCJnT2VjqLxsnRlzG02Qk1Bk53z4P1QaZKjqV001Fe96xm08cGfG3THdN/yiSr1aQ/1fuKDUY049mecM8cTGZtZT87fzx8OjfEfnibmGr0+pulQRfQrfVO6nifuhrjHXC11O3D4pWMrk0Xo2P2G1OTpd+smrYV5OnYsH33UG306E4oK5nc1hJ1tZ2LvLh1kD/XdZ/2CTlEhY9huCkI8zD/w5CheWZPc+yxYZFII8EDfXOLXmIldMgot5nTSudPTB1QgOdKcyQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-dell-mgmt
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-dell-mgmt
  github:
    owner: awseksa
    personal: true
    repository: cluster-definitions
  systemNamespace: flux-system

---
