apiVersion: v1
kind: Secret
metadata:
    name: github-test
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SmoX/5zhqQ==,iv:IrMup3Wetsxk4lAe150s+1yxvwJ/yZTAR/9B5Ju6ibA=,tag:ufljimfpBVD2omCNu4KTgw==,type:str]
    password: ENC[AES256_GCM,data:xfvKhE4hJbnZnpJvSsJvKE9hTmJKMXeUvaf4aaimtw16aCjonTJRXQ==,iv:2P6NoBkVLcs3ffRvdGgJAkVsTsNumh59wAOgRxGwVZw=,tag:EAhUZIaiiNIZ6iJZA3oTGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-06T11:21:17Z"
    mac: ENC[AES256_GCM,data:+RluYE5LTz62nBEltKz8q2+qiia6OBu8QF8oWR3mwiRKJUnUCbtrNl768mn1rym0hjPJzDixamEXy1yvTYYIclbG+9Dbj5hVdjB6oXrhjw8eY1yIyWVJOL/9lzZqx+ajgQjBuwnkWQjPjWcUCVstT/r1U4FS+Dh8NQqtc9pVIck=,iv:SmDhRu1aOuiWIdeLogCQA5fjR/Opz5EvfaZ1kFPBncs=,tag:SsGWtH6d8zZMvMZBRmv/pg==,type:str]
    pgp:
        - created_at: "2024-11-06T11:21:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7cxbW+q6X7VAQ/+No1LRDxHpjCfnSuVcWKK4an6P0Ux6nXMmLuP7yIJoL+j
            Exoc0f8Mzpj+O9MH9NwVuTBX9yA3co/CyTRLLpRYmL+X/E1vW+Owgg4KVAn0qjJ5
            8EcTJHOPgJ+ndtRPUMIl+2dLbgysK5/X2mH4JT/xwziwoU1ef/FH1+ScgfL6aPUd
            7fVCe4Ks6PN3d4lf8bpd1smHLPB0/LbWzzYVsPJPqBbFVRz/Wpe6YjEsgrIjNDP8
            drV2YWvmkWV3PiDGxf5xuGJeQ+I0sNqXLU/dgmZPb2xtuOe5aT7FfOazT9e/gaSv
            duZDCm8vXTcedKokJS+cCrRUr4q9PrqeQ7UY9yoOzKVYWz4XVLczOL9N9VCrW8MF
            hnRtjAlX/+RSLqhfnHaIyrh2T/eelX/+hFaDxeDXvcYUQ93G+xE6aMyEWIlZ8UZb
            1h21DxeuXq+a5uQT9O5WETzCAW0+zG75GgQn6sH+pnMqN0d6hzGGAWFQT1BYMEFr
            rHfjQGUqdQtKmDhfGxvIJFb+iPEl+Kv66fK1l8ZR69Z9zzlMp63wZWAH47T9gr2o
            XoEft711QY+1Ohy3/rejCZM4AV/3xjdiu/iOvIoZwUJzMXtJCtK2LlYpMb6ADfwM
            WHKt9qc3yuLmhumJUh9NtATu+mgAiu5IwuHpV0trcIZKgvL1TLyMji7LJ2rv/VvS
            XAFfza1BaxwP4e6fBNZAH9hm2uvEUdU+Dz2P39Km7pqVRhYXOSktBNvBhvhE/htH
            BTwwL4G189Kqy7JVopdqRUQJMNu8Ihxv427CEOL8fhvvC7OgDzuP6xByUNcP
            =j9wC
            -----END PGP MESSAGE-----
          fp: 7C1C8D4CACEE1A81C196E0798D01222BD13CEAC3
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
